CREATE SEQUENCE SEQ_ROTA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CAMINHAO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE T_REC_ROTA(
    id_rota INTEGER DEFAULT SEQ_ROTA.nextval PRIMARY KEY,
    nm_rota VARCHAR2(100) NOT NULL,
    ds_inicio VARCHAR2(100) NOT NULL,
    ds_final VARCHAR2(100) NOT NULL
);

CREATE TABLE T_REC_CAMINHAO(
    id_caminhao INTEGER DEFAULT SEQ_CAMINHAO.nextval PRIMARY KEY,
    id_rota INTEGER NOT NULL,
    nr_capacidade NUMERIC(7,2) NOT NULL,
    tx_local_temp_real VARCHAR2(100) NOT NULL,
    tx_placa VARCHAR2(7),
    st_servico NUMBER(1) NOT NULL,
    CONSTRAINT fk_rota FOREIGN KEY (id_rota) REFERENCES T_REC_ROTA(id_rota)
);