name: Pipeline CI/CD

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build, Test and Package
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Build and Test
        run: mvn clean package
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-artifact
          path: target/*.jar

  deploy_staging:
    name: Deploy to Staging
    if: github.ref == 'refs/heads/staging'
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: java-artifact
      - name: Deploy to Staging
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh staging

  deploy_production:
    name: Deploy to Production
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://www.seusite.com
    steps:
      - uses: actions/checkout@v3
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: java-artifact
      - name: Deploy to Production
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh production
