name: Staging Deployment - Aplicando Técnicas de DevOps

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Maven Build
        run: mvn clean package
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: rgappcoletafiapads.azurecr.io
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t rgappcoletafiapads.azurecr.io/coleta-app:staging .
          docker push rgappcoletafiapads.azurecr.io/coleta-app:staging

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: rgappcoletafiapads
          slot-name: staging
          images: rgappcoletafiapads.azurecr.io/coleta-app:staging
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}