name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build and run unit tests
        run: mvn clean test

  contract-tests:
    runs-on: ubuntu-latest
    needs: continuous-integration
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Run contract tests
        run: mvn test -Dtest=*ContractTest

  feature-tests:
    runs-on: ubuntu-latest
    needs: continuous-integration
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Run feature tests
        run: mvn test -Dcucumber.options="src/test/resources/features"

  deploy:
    runs-on: ubuntu-latest
    needs: [continuous-integration, contract-tests, feature-tests]
    if: success()
    steps:
      - name: Deploy application
        run: |
          echo "Publicando..."